// Generated by https://quicktype.io

export interface TopLevel {
    id_maestro?: number;
    nombre?:     string;
    apodo?:      string;
    correo?:    string;
    tel?:       string;
    foto?:      string;
}
