// Generated by https://quicktype.io

export interface TopLevel {
    id_maestro?: number;
    nombre?:     string;
    apodo?:      string;
    correo?:    string;
    tel?:       string;
    foto?:      string;
}

export interface Comics {
    comic_id?: number,
    portada?: string;
    titulo?: string;
    descripcion?: string;
    fecha_publicacion?: string,
    genero?: string

  }

  export interface Yuser{
    id?: number,
    nombre?: string,
    correo?: string,
    contrasena?: string
  }
  
